# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 620497a9f6b445c34d5cde6221c6d1bad1e05f3bdc29c75445f88bd0f78f57590136c0e1bb450659fd156e85085be621c11eb8ce820e5aed7235b089e6676613

test:
  secret_key_base: 2ad0ed4a1549c3657343fc3e606f542f6f90033196a5061b5ab8f9be22ee9370e29a2a3f24f0ce124b1a5d34f7c04be161e31438e482451d5e77e6e67a404b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
